apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
  template:
    metadata:
      name: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/dioguerra/ArgoProject.git
        targetRevision: main
        path: argocd
      destination:
        name: '{{cluster}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
